<upgrade>
	<phrases>
		<phrase>
			<module_id>fevent</module_id>
			<version_id>3.5.0beta1</version_id>
			<var_name>item_phrase</var_name>
			<added>1352730940</added>
			<value>fevent</value>
		</phrase>
	</phrases>
	<sql><![CDATA[a:1:{s:9:"ADD_FIELD";a:1:{s:12:"phpfox_fevent";a:1:{s:13:"total_dislike";a:4:{i:0;s:7:"UINT:10";i:1;s:1:"0";i:2;s:0:"";i:3;s:2:"NO";}}}}]]></sql>
</upgrade>